name: cateringyeventos
favicon: null
layout_spectrum: 0.88983
typography_spectrum: 0.25271
title: 'Catering y Eventos '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ce232d'
    - '#000000'
    - '#8b6324'
    - '#ff8080'
  brandStrength: 0.75
  lightness: 0.44362586457282305
  saturation: 0.43552443548105657
  rhythmicContrast: 1
purpose: []
