name: cateringyeventos
favicon: null
layout_spectrum: 0.88983
typography_spectrum: 0.18154
title: 'Catering y Eventos '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ce232d'
    - '#000000'
    - '#8b6324'
    - '#ff8080'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
